{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "trackone.namespace" . }}
  labels:
    app.kubernetes.io/name: trackone
    {{ include "trackone.commonLabels" . | nindent 4 }}
{{- end }}
