apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"trackone"},"name":"trackone"}}
  creationTimestamp: "2026-01-14T23:45:21Z"
  labels:
    app.kubernetes.io/name: trackone
    kubernetes.io/metadata.name: trackone
  name: trackone
  resourceVersion: "731"
  uid: a7d08b9f-22bc-49b8-9ea5-e62485d2a6d3
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
