apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

  - ots/calendar-deployment.yaml
  - ots/calendar-service.yaml
  - ots/calendar-pvc.yaml

  - postgres/postgres-secret.yaml
  - postgres/postgres-statefulset.yaml
  - postgres/postgres-service.yaml
  - postgres/postgres-pvc.yaml

  - gateway/gateway-deployment.yaml
  - gateway/gateway-service.yaml
