{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ include "trackone.namespace" . }}
  labels:
    app.kubernetes.io/name: postgres
    {{- include "trackone.commonLabels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: postgres
  ports:
    - name: pg
      port: {{ .Values.postgres.service.port }}
      targetPort: pg
  type: ClusterIP
{{- end }}
