apiVersion: v1
kind: Service
metadata:
  name: ots-calendar
  namespace: trackone
  labels:
    app.kubernetes.io/name: ots-calendar
spec:
  selector:
    app.kubernetes.io/name: ots-calendar
  ports:
    - name: http
      port: 8468
      targetPort: http
  type: ClusterIP
